### ISSUE TITLE
saveCache does not use lock

### ISSUE THREAD

**Issue by matej21** [nette/robot-loader#11]
- bug report? yes
- version: 3.0.1

saveCache does not use lock and therefore it may fail [on this line](https://github.com/nette/robot-loader/blob/f8f87c979be88e9b6ebd50df7975326423bbe99f/src/RobotLoader/RobotLoader.php#L414) with following error
```
E_WARNING: rename(/root/ss/temp/tests/cache/Nette.RobotLoader/b118fb0ce0dea7bbc63b1ce28466196d.php.tmp,/root/ss/temp/tests/cache/Nette.RobotLoader/b118fb0ce0dea7bbc63b1ce28466196d.php): No such file or directory
   
   in /root/ss/vendor/nette/robot-loader/src/RobotLoader/RobotLoader.php(414) rename()
   in /root/ss/vendor/nette/robot-loader/src/RobotLoader/RobotLoader.php(96) Nette\Loaders\RobotLoader->saveCache()
   in [internal function]Nette\Loaders\RobotLoader->tryLoad()
   in [internal function]spl_autoload_call()
....
```

**Comment by dg** [comment]
Do you have an idea how to solve it?

**Comment by JanTvrdik** [comment]
1) use lock
2) use `@rename(...)` + `is_file` check in case of failure
3) generate random suffix for temporary file

**Comment by JanTvrdik** [comment]
Unfortunately, it still does not seem to work reliably.

To replicate it's enough to run the following scripts multiple time in parallel after `temp` directory has been clear.

~~~
<?php declare(strict_types = 1);

require __DIR__ . '/../../vendor/autoload.php';

$loader = new Nette\Loaders\RobotLoader;
$loader->setAutoRefresh(true);
$loader->setTempDirectory(__DIR__ . '/../temp');
$loader->addDirectory(__DIR__);
$loader->register();

assert(class_exists(Foo::class) === true);
assert(class_exists(Unknown::class) === false);
~~~

Occasionally it fails with error

> Warning: rename(.../temp/aed3679f15f72267b5350e48491c0e0e.phpefeebef3986753080eda337bc0681ea6.tmp,C:\posobota\_robotloader\src/../temp/aed3679f15f72267b5350e48491c0e0e.php): Access is denied. (code: 5) in C:\posobota\vendor\nette\robot-loader\src\RobotLoader\RobotLoader.php on line 415

**Comment by dg** [comment]
Can you fix it somehow?

**Comment by ondrejmirtes** [comment]
I'm experiencing this often when implementing parallel analysis in PHPStan. But only on Windows. I think it might be because the system only allows one process to write to a file at a time, so the rename() sometimes isn't successful.

**Comment by dg** [comment]
It seems that file cannot be deleted / renamed on Windows if it is open. So when PHP is reading it (`include $file`), renaming will fail.

So I'll use read lock.

**Comment by paveljanda** [comment]
Sadly, on our projects, robot-loader stopped working in gitlab CI pipeline after updating package to 3.2.2:

```
Unable to create or acquire shared lock on file '/builds/.......some-package...../tests/integration/../../tests/temp/cache/nette.application/dc419f19af  
   b02aef8183855ed290885d.php
```

I will provide further details if needed.

**Comment by dg** [comment]
😐😣😫😭😭😭

**Comment by dakorpar** [comment]
In my case issue is with dg/bypass finals:

`Warning: file_get_contents(/home/circleci/repo/tests/unit/../../temp/tests/cache/nette.application/c68fd0a35afa3563c5a64085f36d239d.php): failed to open stream: No such file or directory in /home/circleci/repo/vendor/dg/bypass-finals/src/BypassFinals.php on line 205`

**Comment by dg** [comment]
@dakorpar on Windows or Linux?

**Comment by dakorpar** [comment]
windows

**Comment by dg** [comment]
I tried to change the implementation, it should not do it anymore.

**Comment by ondrejmirtes** [comment]
I'll use RobotLoader's dev-master in the next release again and we'll see.
