### ISSUE TITLE
Exlude dir does not work with relative (../..) parent dir

### ISSUE THREAD

**Issue by milo** [nette/robot-loader#13]
- bug report? yes
- feature request? no
- version: 3.0.2

### Description
In Nette application bootstrap, I call:
```php
$configurator->createRobotLoader()
	->addDirectory(__DIR__)
	->addDirectory(__DIR__ . '/../lib')
	->excludeDirectory(__DIR__ . '/../lib/tcpdf')
	->register();
```
but exclusion does not work because on line https://github.com/nette/robot-loader/blob/c3b0c97c04ed82f4d1037a0fd0881f94f9588009/src/RobotLoader/RobotLoader.php#L231
leads to
```php
$disallow === [
    "D:/Web/project/lib/tcpdf" => true,
];

$path === "D:/Web/project/app/../lib/tcpdf";
```

I have two solutions in my mind:
1) Convert path to realpath in `addDirectory()` and:
  a) ignore missing paths
  b) throw an exception on missing paths (BC break probability)
2) Modify mentioned line from `$dir->getPathname()` to `$dir->getRealPath()`.

Which fix would you prefer? Another one?

**Comment by dg** [comment]
getRealPath() seems best, because is called only when refreshing cache, right?

**Comment by milo** [comment]
I think so, good point. I'll open PR.
