### ISSUE TITLE
Ambiguous class $NAME resolution error when there two Classes with same in separate folders

### ISSUE THREAD

**Issue by t2murl** [nette/robot-loader#15]
Version: 3.2.0

### Bug Description
Getting Ambiguous class $NAME resolution error if there two or more Classes with same name in different folders.

**Example**: I have
/app/src/legacy/category/default/actions/CreateAction.php
/app/src/legacy/tags/default/actions/CreateAction.php
and,
when I use "/app/src/legacy/" as autoload_directories (automap) then getting following error.
`Ambiguous class CreateAction resolution; defined in /app/src/legacy/category/default/actions/CreateAction.php and in /app/src/legacy/tags/default/actions/CreateAction.php.`

same error even if I use multiple autoload_directories as:
/app/src/legacy/category/default/actions/
/app/src/legacy/tags/default/actions/

### Possible Solution
Something wrong at line 221 in RobotLoader.php
`if (isset($info['file'])) {
        throw new Nette\InvalidStateException("Ambiguous class $class resolution; defined in {$info['file']} and in $file.");
}`
If I comment-out these lines then everything seems working fine.
:)

**Comment by dg** [comment]
Use `$loader->excludeDirectory('/app/src/legacy/tags');` to exclude duplicated classes.

**Comment by t2murl** [comment]
These two directories are just an example. There are 100s of directories in /legacy/ folder.
And, I want to resolve all the classes from all the directories.

So is that possible? 


---- On Thu, 20 Jun 2019 08:04:01 -0600 notifications@github.com wrote ----



Use $loader->excludeDirectory('/app/src/legacy/tags'); to exclude duplicated classes.

**Comment by dg** [comment]
If two classes have the same name, RobotLoader does not know which one to use. Therefore it cannot be resolved by RobotLoader.
