### ISSUE TITLE
Support for PHP Enums

### ISSUE THREAD

**Issue by Ayesh** [nette/robot-loader#23]
PHP Enum [RFC](https://wiki.php.net/rfc/enumerations) is currently being voted, and it's highly likely that it will pass. 

[Enums support autoloading](https://php.watch/versions/8.1/enums#class-semantics-autoload), and it introduces a new [`T_ENUM` token](https://php.watch/versions/8.1/enums#:~:text=T_ENUM). I would like to suggest that we introduce support to autoload Enums from robot-loader. 

Improve robot-loader to look for `T_ENUM` token _if_ the PHP version is `>= 80100`, and include it in the autoload list.

**Comment by f3l1x** [comment]
👍
