### ISSUE TITLE
Ambiguous class 

### ISSUE THREAD

**Issue by atournayre** [nette/robot-loader#35]
Version: 4.0.2

### Bug Description
In RobotLoader.php line 211:
Ambiguous class Neo\Document resolution; defined in /var/www/symfony/src/Domain/Model/Document/Document.php and in /var/www/symfony/src/Domain/Services/Document/Document.php.  

I'm OK that names are ambiguous but classes resides in different folders and namespaces.

### Steps To Reproduce
I have 2 files :

- /var/www/symfony/src/Domain/Model/Document/Document.php
- /var/www/symfony/src/Domain/Services/Document/Document.php

```php
// /var/www/symfony/src/Domain/Model/Document/Document.php

<?php

namespace Neo\Domain\Model\Document;

class Document {}
```
and
```php
// /var/www/symfony/src/Domain/Services/Document/Document.php

<?php

namespace Neo\Domain\Services\Document;

class Document {}
```

### Expected Behavior
No error

### Possible Solution
Right now, I don't know

**Comment by dg** [comment]
Can you post a link to the minimum repository so I can replicate the bug?

**Comment by atournayre** [comment]
Unfortunately I can't because it's a private repository.
I've tried to put the maximum details in issue.

**Comment by dg** [comment]
Hmmm, unfortunately I can’t help with that.
